### ISSUE TITLE
Vehicles stuck on non-accessible terrain

### ISSUE THREAD

**Issue by cincauhangus** [adityaravishankar/command-and-conquer#54] opened 2012-01-30 19:21 UTC
![vehicles stuck in non-accessible terrain](http://a8.sphotos.ak.fbcdn.net/hphotos-ak-ash4/430913_10151228021795176_841385175_22971230_823609280_n.jpg)

**Comment by adityaravishankar** [comment] 2012-01-30 20:55
Duplicate of the first bug ever...
https://github.com/adityaravishankar/command-and-conquer/issues/1https://github.com/adityaravishankar/command-and-conquer/issues/54

**Closed as completed** 2012-01-31 08:13 UTC
