### ISSUE TITLE
Ore trucks mine too little by default

### ISSUE THREAD

**Issue by deanc** [adityaravishankar/command-and-conquer#27] opened 2012-01-24 10:20 UTC
Gameplay is severely slow at the beginning because ore trucks only mine 100 tiberium each time they come back. I'd suggest raising this value.

**Comment by adityaravishankar** [comment] 2012-01-24 11:16
Could someone who has access to the original game confirm the amount the trucks actually mine per trip? 

I won't be able to check for a while...

**Comment by siromega** [comment] 2012-01-25 06:28
700 units. 

I played C&C a ton in high school. I even have a friend who plays poker with Joe Kucan (the guy who played Kane of NOD in the cut scenes). I'll tell you everything you want to know about C&C.

**Comment by adityaravishankar** [comment] 2012-01-25 07:03
That is awesome... Thanks for helping out :)

Will tweak it to 700... Could you also confirm the cost of a truck? Someone
mentioned I might have got the price off....

**Comment by joeyw** [comment] 2012-01-25 08:35
Heres the game manual, it has all the info about buildings, units, etc.

http://dl.dropbox.com/u/79239/cnc-manual.pdf

**Comment by Wingman4l7** [comment] 2012-01-27 00:05
This is (sort of) a duplicate of issue # 6.

**Comment by adityaravishankar** [comment] 2012-01-27 06:17
Will close # 6 since this has more discussion going on....

**Comment by black-snow** [comment] 2012-01-28 00:51
I just checked the latest(?) version on http://apps.nahklick.de/cnc/. On each tour the harvester unloads 200 funds. The first 100 are added as the container gets pulled up inside the refinery. The second 100 are added as the truck is about to leave the refinery.

@siromega zomfg u srs? please provide a photo of 2012 Kane :)

**Comment by adityaravishankar** [comment] 2012-01-28 12:56
Harvester now mines 700 per trip .... 0.3c released at http://www.adityaravishankar.com/projects/games/command-and-conquer/

**Closed as completed by adityaravishankar** 2012-01-28 12:56 UTC

**Comment by adityaravishankar** [comment] 2012-01-28 13:42
@black-snow The latest version is always at http://www.adityaravishankar.com/projects/games/command-and-conquer/ ... If you see any place that has the old url linked (apps.nahkl......) please ask them to shift to the permanent url..... The temporary url will shut down eventually.....
