### ISSUE TITLE
Tank gets glue to the hill

### ISSUE THREAD

**Issue by joeface** [adityaravishankar/command-and-conquer#37] opened 2012-01-27 09:58 UTC
Tank (see the screenshot) gets glue to the hill and can't to move
http://twitpic.com/8c7uz0

**Comment by adityaravishankar** [comment] 2012-01-27 11:16
Duplicate of https://github.com/adityaravishankar/command-and-conquer/issues/1

**Closed as completed by adityaravishankar** 2012-01-27 11:16 UTC

**Comment by joeface** [comment] 2012-01-27 11:20
ok )
