### ISSUE TITLE
Cursor not changes

### ISSUE THREAD

**Issue by Petrolevb** [adityaravishankar/command-and-conquer#47] opened 2012-01-28 20:35 UTC
The cursor has not to change in the fog war,

In the fog, if you find an ennemie, the move cursor changes to an attack cursor

**Comment by Petrolevb** [comment] 2012-01-28 20:39
Sorry... dupplicate issue

**Comment by adityaravishankar** [comment] 2012-01-29 04:18
Yep... Duplicate of https://github.com/adityaravishankar/command-and-conquer/issues/4

**Closed as completed by adityaravishankar** 2012-01-29 04:18 UTC
