### ISSUE TITLE
Money doesn't come back

### ISSUE THREAD

**Issue by gummimann** [adityaravishankar/command-and-conquer#36] opened 2012-01-26 18:45 UTC
Hello,

When you build item and cancel it, you don't get the money back.

**Comment by Wingman4l7** [comment] 2012-01-27 01:07
Duplicate of issue # 15.

**Comment by adityaravishankar** [comment] 2012-01-27 06:18
https://github.com/adityaravishankar/command-and-conquer/issues/15

**Closed as completed by adityaravishankar** 2012-01-27 06:18 UTC
